### ISSUE TITLE
Spacechains without need for CTV soft fork?

### ISSUE THREAD

**Issue by nerdyrugbyguy** [fiatjaf/simple-ctv-spacechain#1]
Why not do the following to create spacechains while avoiding the need for a soft fork:

-Move a single sat to an address
-Tell everyone the key so it isn't a secret
-Have spacechain miners compete to move the sat within the same address by paying the most fees
-Use op_return to designate the hash of the spacechain block being mined

**Comment by fiatjaf** [comment]
You have basically described spacechains, the problem is that if everybody knows the key anyone will be able to move that sat to some other address and then the spacechain is broken.

If you like these topics join https://t.me/spacechains.

**Comment by nerdyrugbyguy** [comment]
If an attacker wants to pay the fees to steal the sat, the spacechain is easily repaired by moving a new sat to the address.  Due to miner competition, the cost the attacker must pay to break the spacechain is greater than the cost of the repair.  Such an attack is expensive to sustain and yields no reward.

Aren't other methods such as CTV also susceptible to denial of service attacks whereby a malicious minor spends the UTXO without publishing the hash of a valid spacechain block?

**Comment by fiatjaf** [comment]
What if people move multiple sats to that address? Which one is the correct?

**Comment by ErikDeSmedt** [comment]
I think ordinals can fix this

The following convention should work
1. The sat that is owned by the address for the longest time without interruption is valid.
2. If multiple sats are owned equally long, pick the one with the lowest numismatic value according to ordinals theory.

**Comment by nerdyrugbyguy** [comment]
Erik,

I think that would work.  I was going to suggest that all of the UTXOs owned by the address in the previous block must be swept.

Regards,
-nerdyrugbyguy

**Comment by fiatjaf** [comment]
I think you're not measuring correctly the amount of confusion and pain all that would entail.

**Comment by nerdyrugbyguy** [comment]
Let me see if this clarification helps.

Mining a valid spacechain block requires a mainchain  transaction that:
-spends all sats owned by the designated address in the previous block
-outputs at least one sat to the designated address
-outputs an op_return value corresponding to the hash of a valid spacechain block

**Comment by fiatjaf** [comment]
What if there are no sats in the address in the previous block, then multiple miners all try to mine a block at the same time by sending each a different satoshi to the address?

**Comment by nerdyrugbyguy** [comment]
No one can mine when there are no sats in the address of the previous block.

Multiple miners each sending a different sat to the address at the same time would setup the address so that competitive mining can occur in the next block.

Sats would be sent to the address to initially bootstrap the mining process, recover from an attack, or be sent to the address as mining occurs just for fun.  Since spending from the address is competitive, funds sent to the address will likely be turned into mining fees.

**Comment by nerdyrugbyguy** [comment]
Discussion moved to https://t.me/spacechains
